import 'dart:math';
import 'package:flutter/material.dart';

class TipsScreen extends StatefulWidget {
  @override
  _TipsScreenState createState() => _TipsScreenState();
}

class _TipsScreenState extends State<TipsScreen> {
  final List<Map<String, String>> quotes = [
    {'quote': '“The only way to do great work is to love what you do.”', 'author': '- Steve Jobs'},
    {'quote': '“Focus on being productive instead of busy.”', 'author': '- Tim Ferriss'},
    {'quote': '“Success is not the key to happiness. Happiness is the key to success.”', 'author': '- Albert Schweitzer'},
    {'quote': '“Don’t watch the clock; do what it does. Keep going.”', 'author': '- Sam Levenson'},
    {'quote': '“You cannot have a positive life and a negative mind.”', 'author': '- Joyce Meyer'},
    {'quote': '“The future depends on what you do today.”', 'author': '- Mahatma Gandhi'},
    {'quote': '“Believe you can and you’re halfway there.”', 'author': '- Theodore Roosevelt'},
    {'quote': '“Act as if what you do makes a difference. It does.”', 'author': '- William James'},
    {'quote': '“Success usually comes to those who are too busy to be looking for it.”', 'author': '- Henry David Thoreau'},
    {'quote': '“Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.”', 'author': '- Roy T. Bennett'},
    {'quote': '“The best time to plant a tree was twenty years ago. The second best time is now.”', 'author': '- Chinese Proverb'},
    {'quote': '“Your time is limited, so don’t waste it living someone else’s life.”', 'author': '- Steve Jobs'},
    {'quote': '“You miss 100% of the shots you don’t take.”', 'author': '- Wayne Gretzky'},
    {'quote': '“The mind is everything. What you think you become.”', 'author': '- Buddha'},
    {'quote': '“Life is what happens when you’re busy making other plans.”', 'author': '- John Lennon'},
    {'quote': '“The purpose of our lives is to be happy.”', 'author': '- Dalai Lama'},
    {'quote': '“Get busy living or get busy dying.”', 'author': '- Stephen King'},
{'quote': '“You have within you right now, everything you need to deal with whatever the world can throw at you.”', 'author': '- Brian Tracy'},
{'quote': '“Believe you can and you’re halfway there.”', 'author': '- Theodore Roosevelt'},
{'quote': '“The greatest glory in living lies not in never falling, but in rising every time we fall.”', 'author': '- Nelson Mandela'},
{'quote': '“In the end, we will remember not the words of our enemies, but the silence of our friends.”', 'author': '- Martin Luther King Jr.'},
{'quote': '“Do what you can, with what you have, where you are.”', 'author': '- Theodore Roosevelt'},
{'quote': '“Life is either a daring adventure or nothing at all.”', 'author': '- Helen Keller'},
{'quote': '“You are never too old to set another goal or to dream a new dream.”', 'author': '- C.S. Lewis'},
{'quote': '“It does not matter how slowly you go as long as you do not stop.”', 'author': '- Confucius'},
{'quote': '“Hardships often prepare ordinary people for an extraordinary destiny.”', 'author': '- C.S. Lewis'},
{'quote': '“Opportunities dont happen. You create them.”', 'author': '- Chris Grosser'},
{'quote': '“What we think, we become.”', 'author': '- Buddha'},
{'quote': '“Everything you’ve ever wanted is on the other side of fear.”', 'author': '- George Addair'},
{'quote': '“Dream big and dare to fail.”', 'author': '- Norman Vaughan'},
{'quote': '“You can’t use up creativity. The more you use, the more you have.”', 'author': '- Maya Angelou'},
{'quote': '“If you want to lift yourself up, lift up someone else.”', 'author': '- Booker T. Washington'},
{'quote': '“Success is not how high you have climbed, but how you make a positive difference to the world.”', 'author': '- Roy T. Bennett'},
{'quote': '“Success is not in what you have, but who you are.”', 'author': '- Bo Bennett'},
{'quote': '“Dream big and dare to fail.”', 'author': '- Norman Vaughan'},
{'quote': '“You must be the change you wish to see in the world.”', 'author': '- Mahatma Gandhi'},
{'quote': '“Life is 10% what happens to us and 90% how we react to it.”', 'author': '- Charles R. Swindoll'},
{'quote': '“The only limit to our realization of tomorrow will be our doubts of today.”', 'author': '- Franklin D. Roosevelt'},
{'quote': '“It is never too late to be what you might have been.”', 'author': '- George Eliot'},
{'quote': '“You are braver than you believe, stronger than you seem, and smarter than you think.”', 'author': '- A.A. Milne'},
{'quote': '“What lies behind us and what lies before us are tiny matters compared to what lies within us.”', 'author': '- Ralph Waldo Emerson'},
{'quote': '“Do not wait to strike till the iron is hot, but make it hot by striking.”', 'author': '- William Butler Yeats'},
{'quote': '“If you want to live a happy life, tie it to a goal, not to people or things.”', 'author': '- Albert Einstein'},
{'quote': '“Success is walking from failure to failure with no loss of enthusiasm.”', 'author': '- Winston S. Churchill'},
{'quote': '“To succeed in life, you need three things: a wishbone, a backbone and a funny bone.”', 'author': '- Reba McEntire'},
{'quote': '“If you can dream it, you can do it.”', 'author': '- Walt Disney'},
{'quote': '“The only person you are destined to become is the person you decide to be.”', 'author': '- Ralph Waldo Emerson'},
{'quote': '“The best revenge is massive success.”', 'author': '- Frank Sinatra'},
{'quote': '“Act as if what you do makes a difference. It does.”', 'author': '- William James'},
{'quote': '“Success is not the absence of failure; it’s the persistence through failure.”', 'author': '- Aisha Tyler'},
{'quote': '“The only way to do great work is to love what you do.”', 'author': '- Steve Jobs'},
{'quote': '“Life is short, and it is up to you to make it sweet.”', 'author': '- Sarah Louise Delany'},
{'quote': '“If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.”', 'author': '- James Cameron'},
{'quote': '“There are no limits to what you can accomplish, except the limits you place on your own thinking.”', 'author': '- Brian Tracy'},
{'quote': '“Failure is the condiment that gives success its flavor.”', 'author': '- Truman Capote'},
{'quote': '“The road to success and the road to failure are almost exactly the same.”', 'author': '- Colin R. Davis'},
{'quote': '“You can’t have everything. Where would you put it?”', 'author': '- Steven Wright'},
{'quote': '“Success is the sum of small efforts, repeated day in and day out.”', 'author': '- Robert Collier'},
{'quote': '“Success is how high you bounce when you hit bottom.”', 'author': '- George S. Patton'},
{'quote': '“Success is not about how much money you make, but how much of a difference you make in people’s lives.”', 'author': '- Michelle Obama'},
{'quote': '“The only place where success comes before work is in the dictionary.”', 'author': '- Vidal Sassoon'},
{'quote': '“You don’t have to be great to start, but you have to start to be great.”', 'author': '- Zig Ziglar'},
{'quote': '“Strive not to be a success, but rather to be of value.”', 'author': '- Albert Einstein'},
{'quote': '“Success is not a destination, but the road that you’re on.”', 'author': '- Marlon Wayans'},
{'quote': '“The best way to predict your future is to create it.”', 'author': '- Abraham Lincoln'},
{'quote': '“Your life does not get better by chance, it gets better by change.”', 'author': '- Jim Rohn'},
{'quote': '“Success is the ability to go from one failure to another with no loss of enthusiasm.”', 'author': '- Winston S. Churchill'},
{'quote': '“The secret of success is to be ready when your opportunity comes.”', 'author': '- Benjamin Disraeli'},
{'quote': '“Success is a journey, not a destination.”', 'author': '- Arthur Ashe'},
{'quote': '“Success usually comes to those who are too busy to be looking for it.”', 'author': '- Henry David Thoreau'},
{'quote': '“If you want to achieve greatness, stop asking for permission.”', 'author': '- Anonymous'},
{'quote': '“Success is not about being the best. It’s about always getting better.”', 'author': '- Behdad Sami'},
{'quote': '“What we fear doing most is usually what we most need to do.”', 'author': '- Tim Ferriss'},
{'quote': '“Success is getting what you want. Happiness is wanting what you get.”', 'author': '- Dale Carnegie'},
{'quote': '“Success is not in what you have, but who you are.”', 'author': '- Bo Bennett'},
{'quote': '“If you can dream it, you can achieve it.”', 'author': '- Zig Ziglar'},
{'quote': '“Don’t limit your challenges. Challenge your limits.”', 'author': '- Anonymous'},
{'quote': '“In order to succeed, your desire for success should be greater than your fear of failure.”', 'author': '- Bill Cosby'},
{'quote': '“Do not wait to strike till the iron is hot, but make it hot by striking.”', 'author': '- William Butler Yeats'},
{'quote': '“Dream big and dare to fail.”', 'author': '- Norman Vaughan'},
{'quote': '“Success is not the key to happiness. Happiness is the key to success.”', 'author': '- Albert Schweitzer'},
{'quote': '“The only limit to our realization of tomorrow will be our doubts of today.”', 'author': '- Franklin D. Roosevelt'},
{'quote': '“Success is walking from failure to failure with no loss of enthusiasm.”', 'author': '- Winston S. Churchill'},
{'quote': '“You don’t have to be great to start, but you have to start to be great.”', 'author': '- Zig Ziglar'},
{'quote': '“Opportunities dont happen. You create them.”', 'author': '- Chris Grosser'},
{'quote': '“The only person you are destined to become is the person you decide to be.”', 'author': '- Ralph Waldo Emerson'},
{'quote': '“Success is how high you bounce when you hit bottom.”', 'author': '- George S. Patton'},
{'quote': '“The only way to do great work is to love what you do.”', 'author': '- Steve Jobs'},
{'quote': '“To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.”', 'author': '- Reba McEntire'},
{'quote': '“Success is not the absence of failure; it’s the persistence through failure.”', 'author': '- Aisha Tyler'},
{'quote': '“Success is not in what you have, but who you are.”', 'author': '- Bo Bennett'},
{'quote': '“Success is the sum of small efforts, repeated day in and day out.”', 'author': '- Robert Collier'},
{'quote': '“It does not matter how slowly you go as long as you do not stop.”', 'author': '- Confucius'},
{'quote': '“Success is not just what you accomplish in your life, it’s about what you inspire others to do.”', 'author': '- Anonymous'},
{'quote': '“The best way to predict the future is to create it.”', 'author': '- Peter Drucker'},
{'quote': '“You miss 100% of the shots you don’t take.”', 'author': '- Wayne Gretzky'},
{'quote': '“The future belongs to those who believe in the beauty of their dreams.”', 'author': '- Eleanor Roosevelt'},
{'quote': '“Success is liking yourself, liking what you do, and liking how you do it.”', 'author': '- Maya Angelou'},
{'quote': '“Success is not about how much money you make, but how much of a difference you make in people’s lives.”', 'author': '- Michelle Obama'},
{'quote': '“What we think, we become.”', 'author': '- Buddha'},
{'quote': '“You can’t have everything. Where would you put it?”', 'author': '- Steven Wright'},
{'quote': '“Do not wait for leaders; do it alone, person to person.”', 'author': '- Mother Teresa'},
{'quote': '“The best revenge is massive success.”', 'author': '- Frank Sinatra'},
{'quote': '“Success is often achieved by those who don’t know that failure is inevitable.”', 'author': '- Coco Chanel'},
{'quote': '“The secret of success is to be ready when your opportunity comes.”', 'author': '- Benjamin Disraeli'},
{'quote': '“Success is the ability to go from one failure to another with no loss of enthusiasm.”', 'author': '- Winston S. Churchill'},
{'quote': '“You must do the things you think you cannot do.”', 'author': '- Eleanor Roosevelt'},
{'quote': '“Success is the sum of small efforts, repeated day in and day out.”', 'author': '- Robert Collier'},
{'quote': '“Success is the result of preparation, hard work, and learning from failure.”', 'author': '- Colin Powell'},
{'quote': '“Success is a journey, not a destination.”', 'author': '- Arthur Ashe'},
{'quote': '“What lies behind us and what lies before us are tiny matters compared to what lies within us.”', 'author': '- Ralph Waldo Emerson'},
{'quote': '“If you really look closely, most overnight successes took a long time.”', 'author': '- Steve Jobs'},
{'quote': '“To succeed, you have to believe in something with such a passion that it becomes a reality.”', 'author': '- Anita Roddick'},
{'quote': '“Success is how high you bounce when you hit bottom.”', 'author': '- George S. Patton'},
{'quote': '“You can’t build a reputation on what you are going to do.”', 'author': '- Henry Ford'},
{'quote': '“What separates the winners from the losers is how a person reacts to each new twist of fate.”', 'author': '- Donald Trump'},
{'quote': '“Success is not just about what you accomplish in your life; it’s about what you inspire others to do.”', 'author': '- Anonymous'},
{'quote': '“Success comes from knowing that you did your best to become the best that you are capable of becoming.”', 'author': '- John Wooden'},
{'quote': '“The only place where success comes before work is in the dictionary.”', 'author': '- Vidal Sassoon'},
{'quote': '“Success is not about how much money you make, but how much of a difference you make in people’s lives.”', 'author': '- Michelle Obama'},
{'quote': '“Success is a lousy teacher. It seduces smart people into thinking they can’t lose.”', 'author': '- Bill Gates'},
{'quote': '“To be successful, you must first believe that you can be.”', 'author': '- Nikos Kazantzakis'},
{'quote': '“Success is not in what you have, but who you are.”', 'author': '- Bo Bennett'},
{'quote': '“There is no failure except in no longer trying.”', 'author': '- Elbert Hubbard'},
{'quote': '“It’s not whether you get knocked down, it’s whether you get up.”', 'author': '- Vince Lombardi'},
{'quote': '“The man who moves a mountain begins by carrying away small stones.”', 'author': '- Confucius'},
{'quote': '“There are no limits to what you can accomplish, except the limits you place on your own thinking.”', 'author': '- Brian Tracy'},
{'quote': '“Success is the result of preparation, hard work, and learning from failure.”', 'author': '- Colin Powell'},
{'quote': '“You don’t have to be great to start, but you have to start to be great.”', 'author': '- Zig Ziglar'},
{'quote': '“The future depends on what you do today.”', 'author': '- Mahatma Gandhi'},
{'quote': '“Success is not how high you have climbed, but how you make a positive difference to the world.”', 'author': '- Roy T. Bennett'},
{'quote': '“Success usually comes to those who are too busy to be looking for it.”', 'author': '- Henry David Thoreau'},
{'quote': '“Life is not about finding yourself. Life is about creating yourself.”', 'author': '- George Bernard Shaw'},
{'quote': '“Success is a journey, not a destination.”', 'author': '- Arthur Ashe'},
{'quote': '“You cannot have a positive life and a negative mind.”', 'author': '- Joyce Meyer'},
{'quote': '“What we fear doing most is usually what we most need to do.”', 'author': '- Tim Ferriss'},
{'quote': '“The road to success is dotted with many tempting parking spaces.”', 'author': '- Will Rogers'},
    {'quote': '“If you want to live a happy life, tie it to a goal, not to people or things.”', 'author': '- Albert Einstein'},
    {'quote': '“I find that the harder I work, the more luck I seem to have.”', 'author': '- Thomas Jefferson'},
    {'quote': '“Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.”', 'author': '- Booker T. Washington'},
    {'quote': '“If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward.”', 'author': '- Martin Luther King Jr.'},
    {'quote': '“Success is a state of mind. If you want success, start thinking of yourself as a success.”', 'author': '- Joyce Brothers'},
    {'quote': '“Success is not final, failure is not fatal: It is the courage to continue that counts.”', 'author': '- Winston Churchill'},
    {'quote': '“Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.”', 'author': '- Christian D. Larson'},
    {'quote': '“Success is not measured by what you accomplish, but by the opposition you have encountered.”', 'author': '- Orison Swett Marden'},
    {'quote': '“Your time is limited, so don’t waste it living someone else’s life.”', 'author': '- Steve Jobs'},
    {'quote': '“You may have to fight a battle more than once to win it.”', 'author': '- Margaret Thatcher'},
    {'quote': '“Success is getting what you want. Happiness is wanting what you get.”', 'author': '- Dale Carnegie'},
    {'quote': '“It is hard to fail, but it is worse never to have tried to succeed.”', 'author': '- Theodore Roosevelt'},
    {'quote': '“The successful warrior is the average man, with laser-like focus.”', 'author': '- Bruce Lee'},
    {'quote': '“You don’t find will power; you create it.”', 'author': '- Anonymous'},
    {'quote': '“Success is where preparation and opportunity meet.”', 'author': '- Bobby Unseld'},
    {'quote': '“The way to get started is to quit talking and begin doing.”', 'author': '- Walt Disney'},
    {'quote': '“The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.”', 'author': '- Vince Lombardi'},
    {'quote': '“The future belongs to those who prepare for it today.”', 'author': '- Malcolm X'},
    {'quote': '“Success is the maximum utilization of the ability that you have.”', 'author': '- Zig Ziglar'},
    {'quote': '“Don’t let yesterday take up too much of today.”', 'author': '- Will Rogers'},
    {'quote': '“Life is what we make it, always has been, always will be.”', 'author': '- Grandma Moses'},
    {'quote': '“Setting goals is the first step in turning the invisible into the visible.”', 'author': '- Tony Robbins'},
    {'quote': '“Success is the result of small efforts, repeated day in and day out.”', 'author': '- Robert Collier'},
    {'quote': '“If you are not willing to risk the usual, you will have to settle for the ordinary.”', 'author': '- Jim Rohn'},
    {'quote': '“A successful man is one who can lay a firm foundation with the bricks others have thrown at him.”', 'author': '- David Brinkley'},
    {'quote': '“If you want to succeed, you have to be willing to be uncomfortable.”', 'author': '- Anonymous'},
    {'quote': '“The successful man is the one who finds out what is the matter with his business before his competitors do.”', 'author': '- Roy L. Smith'},
    {'quote': '“Success is a journey, not a destination. The doing is often more important than the outcome.”', 'author': '- Arthur Ashe'},
    {'quote': '“The best way to predict your future is to create it.”', 'author': '- Abraham Lincoln'},
    {'quote': '“Success means having the courage, the determination, and the will to become the person you believe you were meant to be.”', 'author': '- George A. Sheehan'},
    {'quote': '“Success is often the result of taking a misstep in the right direction.”', 'author': '- Al Bernstein'},
    {'quote': '“To achieve success, whatever the job we have, we must carry ourselves with a spontaneous enthusiasm for the work we do.”', 'author': '- Dale Carnegie'},
    {'quote': '“Success is not just about what you accomplish in your life; it’s about what you inspire others to do.”', 'author': '- Anonymous'},
    {'quote': '“Success is achieved and maintained by those who try and keep trying.”', 'author': '- W. Clement Stone'},
    {'quote': '“Success is how high you bounce when you hit bottom.”', 'author': '- George S. Patton'},
    {'quote': '“Success is not for the lazy.”', 'author': '- Anonymous'},
    {'quote': '“Success requires a level of risk. You cannot achieve greatness without taking risks.”', 'author': '- Anonymous'},
    {'quote': '“You must expect great things of yourself before you can do them.”', 'author': '- Michael Jordan'},
    {'quote': '“Success doesn’t come from what you do occasionally, it comes from what you do consistently.”', 'author': '- Marie Forleo'},
    {'quote': '“Keep your eyes on the stars, and your feet on the ground.”', 'author': '- Theodore Roosevelt'},
    {'quote': '“Success isn’t just about what you accomplish in your life, it’s about what you inspire others to do.”', 'author': '- Anonymous'},
    {'quote': '“Success is the progressive realization of a worthy goal.”', 'author': '- Earl Nightingale'},
    {'quote': '“Success is how high you bounce when you hit bottom.”', 'author': '- George S. Patton'},
    {'quote': '“You can’t build a reputation on what you are going to do.”', 'author': '- Henry Ford'},
    {'quote': '“Success is going from failure to failure without losing your enthusiasm.”', 'author': '- Winston Churchill'},
    {'quote': '“You can’t wait for inspiration. You have to go after it with a club.”', 'author': '- Jack London'},
    {'quote': '“A person who never made a mistake never tried anything new.”', 'author': '- Albert Einstein'},
    {'quote': '“Success is what happens after you have survived all your mistakes.”', 'author': '- Anne Lamott'},
    {'quote': '“I never dreamed about success. I worked for it.”', 'author': '- Estée Lauder'},
    {'quote': '“Success is the sum of small efforts, repeated day in and day out.”', 'author': '- Robert Collier'},
    {'quote': '“Success is not in what you have, but who you are.”', 'author': '- Bo Bennett'},
    {'quote': '“Success is the maximum utilization of the ability that you have.”', 'author': '- Zig Ziglar'},
    {'quote': '“Success is a journey, not a destination.”', 'author': '- Arthur Ashe'},
    {'quote': '“There is no failure. Only feedback.”', 'author': '- Robert Allen'},
    {'quote': '“Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.”', 'author': '- Booker T. Washington'},
    {'quote': '“Success is what you make it.”', 'author': '- Anonymous'},
    {'quote': '“Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.”', 'author': '- Christian D. Larson'},
    {'quote': '“Success is often achieved by those who don’t know that failure is inevitable.”', 'author': '- Coco Chanel'},
    {'quote': '“The only place where success comes before work is in the dictionary.”', 'author': '- Vidal Sassoon'},
    {'quote': '“You don’t have to be great to start, but you have to start to be great.”', 'author': '- Zig Ziglar'},
    {'quote': '“Success usually comes to those who are too busy to be looking for it.”', 'author': '- Henry David Thoreau'},
    {'quote': '“The best way to predict the future is to create it.”', 'author': '- Abraham Lincoln'},
    {'quote': '“Success is a journey, not a destination.”', 'author': '- Arthur Ashe'},
  ];



  List<Map<String, String>> shuffledQuotes = [];

  @override
  void initState() {
    super.initState();
    shuffleQuotes();
  }

  void shuffleQuotes() {
    setState(() {
      shuffledQuotes = List.from(quotes)..shuffle();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Tips & Quotes'),
      ),
      body: RefreshIndicator(
        onRefresh: () async {
          shuffleQuotes(); // Shuffle quotes when the user pulls down
        },
        child: ListView.builder(
          itemCount: shuffledQuotes.length,
          itemBuilder: (context, index) {
            return Container(
              margin: EdgeInsets.all(8.0),
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(12),
                gradient: LinearGradient(
                  colors: [
                    Colors.blueAccent.withOpacity(0.7),
                    Colors.purpleAccent.withOpacity(0.7),
                  ],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
              ),
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      shuffledQuotes[index]['quote']!,
                      style: TextStyle(
                        fontSize: 18,
                        fontStyle: FontStyle.italic,
                        color: Colors.white,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    SizedBox(height: 8),
                    Text(
                      shuffledQuotes[index]['author']!,
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                        color: Colors.white70,
                      ),
                      textAlign: TextAlign.right,
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
